baseurl: "https://yihui.org/"
languageCode: "en-us"
title: "Yihui Xie | 谢益辉"
theme: "hugo-ivy"
disqusShortname: "yihui"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "菜谱"
      url: "/cn/recipe/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6
  knitr:
    - name: "Home"
      url: "/knitr/"
      weight: 1
    - name: "Options"
      url: "/knitr/options/"
      weight: 2
    - name: "Hooks"
      url: "/knitr/hooks/"
      weight: 3
    - name: "Examples"
      url: "/knitr/demos/"
      weight: 4
    - name: "FAQ"
      url: "/knitr/faq/"
      weight: 5
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/knitr"
      weight: 6
    - name: "Yihui Xie"
      url: "/"
      weight: 7
  animation:
    - name: "Home"
      url: "/animation/"
      weight: 1
    - name: "Examples"
      url: "/animation/examples/"
      weight: 2
    - name: "Export"
      url: "/animation/export/"
      weight: 3
    - name: "Resources"
      url: "/animation/resources/"
      weight: 4
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/animation"
      weight: 5
    - name: "Yihui Xie"
      url: "/"
      weight: 6
  tinytex:
    - name: "Home"
      url: "/tinytex/"
      weight: 1
    - name: "FAQs"
      url: "/tinytex/faq/"
      weight: 2
    - name: "R package"
      url: "/tinytex/r/"
      weight: 3
    - name: "Hall of Pain"
      url: "/tinytex/pain/"
      weight: 4
    - name: "中文文档"
      url: "/tinytex/cn/"
      weight: 5
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/tinytex"
      weight: 6
    - name: "Yihui Xie"
      url: "/"
      weight: 7

params:
  description: "Personal website of Yihui Xie; 谢益辉的个人网站"
  footer: "&copy; [Yihui Xie](/) 2005 - 2020"
  disqusURL: "https://yihui.org"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/rbind/yihui/edit/master/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Yihui Xie"
      tag: ""
    knitr:
      img: "/knitr/images/knit-logo.png"
      url: "/knitr/"
      alt: "knitr logo"
      tag: "knitr: elegant, flexible, and fast dynamic report generation with R"
    tinytex:
      img: "/images/logo-tinytex.png"
      url: "/tinytex/"
      alt: "tinytex logo"
      tag: "TinyTeX: A lightweight and easy-to-maintain LaTeX distribution"

  author:
    en: "Yihui Xie"
    cn: "谢益辉"
    animation: "Yihui Xie & Lijia Yu"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
