baseurl: "https://yihui.name/"
languageCode: "en-us"
title: "Yihui Xie | 谢益辉"
theme: "hugo-lithium-theme"
googleAnalytics: "UA-1988641-2"
disqusShortname: "yihui"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "博客"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "English"
      url: "/en/"
      weight: 5
  knitr:
    - name: "Home"
      url: "/knitr/"
      weight: 1
    - name: "Options"
      url: "/knitr/options/"
      weight: 2
    - name: "Hooks"
      url: "/knitr/hooks/"
      weight: 3
    - name: "Examples"
      url: "/knitr/demos/"
      weight: 4
    - name: "FAQ"
      url: "/knitr/faq/"
      weight: 5
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/knitr"
      weight: 6
  animation:
    - name: "Home"
      url: "/animation/"
      weight: 1
    - name: "Examples"
      url: "/animation/examples/"
      weight: 2
    - name: "Export"
      url: "/animation/export/"
      weight: 3
    - name: "Resources"
      url: "/animation/resources/"
      weight: 4
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/animation"
      weight: 5

params:
  description: "Personal website of Yihui Xie; 谢益辉的个人网站"
  disqusURL: "http://yihui.name"
  dateFormat: "2006/01/02"
  customCSS: ["css/custom.css"]
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
  githubContentURL: "https://github.com/rbind/yihui/edit/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.11.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  MathJaxVersion: "2.7.1"
  MathJaxCDN: "//cdn.bootcss.com"

  social:
    twitter: "xieyihui"
    weibo: "谢益辉"
    weibo_url: "yihuixie"
    github: "yihui"

  logo:
    url: "logo.png"
    width: 50
    height: 50
    alt: "Yihui Xie"

  author:
    en: "Yihui Xie"
    cn: "谢益辉"
    animation: "Yihui Xie & Lijia Yu"

  lang:
    edit:
      en: "Suggest an edit of this page"
      cn: "编辑本页"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
